FROM radu.boian/ownzones_challenge

WORKDIR /usr/radu_boian/app

COPY tests tests
COPY package.json package.json 
COPY tsconfig.json tsconfig.json 

RUN npm update && \
    npm install -g mocha

CMD ["mocha", "-r",  "ts-node/register",  "./tests/*.ts"]