FROM node:8

WORKDIR /usr/radu_boian/app

COPY src src
COPY resources resources
COPY tests tests
COPY package.json package.json 
COPY tsconfig.json tsconfig.json 

RUN npm install

RUN npm run build

CMD ["node", "dist/server.js"]